# Sesión 2 — Regresión lineal con dos variables (Pero se pueden más XD)

**Objetivo:** conectar el trabajo algebraico manual con un modelo entrenado en Python.

En esta práctica usamos el modelo:

\[
y = a_1 x_1 + a_2 x_2 + b
\]

donde:
- `x1` = horas de estudio
- `x2` = horas de sueño
- `y` = calificación

In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Dataset pequeño para comparar con la hoja de trabajo
df = pd.DataFrame({
    "x1_estudio": [1, 2, 3, 4],
    "x2_sueno": [8, 7, 6, 5],
    "y_calificacion": [60, 65, 70, 75]
})

df

   x1_estudio  x2_sueno  y_calificacion
0           1         8              60
1           2         7              65
2           3         6              70
3           4         5              75

## 1. Observa los datos

Antes de entrenar el modelo, responde en tu hoja (En la última hoja en la parte en blanco coloca las respuestas numeradas, por ejemplo 1.1...):

1. ¿Qué variable parece aumentar la calificación?
2. ¿Qué variable parece disminuirla?
3. ¿Qué esperas que pase con los coeficientes del modelo?

In [2]:
X = df[["x1_estudio", "x2_sueno"]]
y = df["y_calificacion"]

model = LinearRegression()
model.fit(X, y)

a1, a2 = model.coef_
b = model.intercept_

print("a1 =", a1)
print("a2 =", a2)
print("b =", b)

a1 = 2.5
a2 = -2.5
b = 77.5

## 2. Compara con tu trabajo manual

Escribe en tu hoja:

- ¿Qué tan cerca quedaron tus valores de `a1`, `a2` y `b`?
- ¿Por qué crees que el programa encuentra estos valores tan rápido?

In [3]:
pred = model.predict(X)

results = df.copy()
results["prediccion"] = pred
results["error"] = results["y_calificacion"] - results["prediccion"]
results

   x1_estudio  x2_sueno  y_calificacion  prediccion  error
0           1         8              60        60.0    0.0
1           2         7              65        65.0    0.0
2           3         6              70        70.0    0.0
3           4         5              75        75.0    0.0

In [4]:
mae = mean_absolute_error(y, pred)
mse = mean_squared_error(y, pred)
r2 = r2_score(y, pred)

print("MAE =", mae)
print("MSE =", mse)
print("R^2 =", r2)

MAE = 0.0
MSE = 0.0
R^2 = 1.0

## 3. Cambia los datos para ver el error

Ahora agregaremos un dato que no sigue exactamente el mismo patrón.

In [5]:
df2 = pd.DataFrame({
    "x1_estudio": [1, 2, 3, 4, 5, 6],
    "x2_sueno": [8, 7, 6, 5, 4, 6],
    "y_calificacion": [60, 65, 70, 75, 78, 80]
})

X2 = df2[["x1_estudio", "x2_sueno"]]
y2 = df2["y_calificacion"]

model2 = LinearRegression()
model2.fit(X2, y2)

pred2 = model2.predict(X2)

results2 = df2.copy()
results2["prediccion"] = pred2.round(2)
results2["error"] = (results2["y_calificacion"] - results2["prediccion"]).round(2)
results2

   x1_estudio  x2_sueno  y_calificacion  prediccion  error
0           1         8              60        60.4   -0.4
1           2         7              65        65.0    0.0
2           3         6              70        69.6    0.4
3           4         5              75        74.2    0.8
4           5         4              78        78.8   -0.8
5           6         6              80        80.0    0.0

In [6]:
print("a1 =", model2.coef_[0])
print("a2 =", model2.coef_[1])
print("b =", model2.intercept_)

print("MAE =", mean_absolute_error(y2, pred2))
print("MSE =", mean_squared_error(y2, pred2))
print("R^2 =", r2_score(y2, pred2))

a1 = 3.466666666666668
a2 = -1.1333333333333337
b = 66.0
MAE = 0.40000000000000213
MSE = 0.2666666666666695
R^2 = 0.9947252747252747

## 4. Reflexión final

Completa en tu hoja:

1. ¿Qué cambió cuando los datos dejaron de ajustarse de manera perfecta?
2. ¿Por qué ahora tiene sentido hablar de *error*?
3. ¿Qué valor tiene hacer el cálculo a mano antes de usar una librería?